export type ScriptBlockType =
  | 'import'
  | 'variable'
  | 'function'
  | 'if'
  | 'console_log'
  | 'return'
  | 'expression';

export type ScriptMode = 'module' | 'function';

export interface ScriptBlock {
  id: string;
  type: ScriptBlockType;
  label: string;
  path?: string;
  variableName?: string;
  value?: string;
  functionName?: string;
  params?: string;
  condition?: string;
  message?: string;
  expression?: string;
  children: ScriptBlock[];
}

const BLOCK_DEFAULTS: Record<ScriptBlockType, Partial<ScriptBlock>> = {
  import: {
    label: 'Import',
    path: 'module-name',
    variableName: 'name',
  },
  variable: {
    label: 'Declare variable',
    variableName: 'myVar',
    value: '42',
  },
  function: {
    label: 'Function',
    functionName: 'myFunction',
    params: '',
  },
  if: {
    label: 'If statement',
    condition: 'true',
  },
  console_log: {
    label: 'Log',
    message: 'Hello world',
  },
  return: {
    label: 'Return',
    expression: 'value',
  },
  expression: {
    label: 'Expression',
    expression: '/* code */',
  },
};

let blockCounter = 0;

export function createScriptBlock(
  type: ScriptBlockType,
  overrides: Partial<Omit<ScriptBlock, 'id' | 'type' | 'children'>> = {}
): ScriptBlock {
  const defaults = BLOCK_DEFAULTS[type] || {};
  return {
    id: `block_${++blockCounter}_${Date.now().toString(36)}`,
    type,
    label: defaults.label ?? type,
    children: [],
    ...defaults,
    ...overrides,
  } as ScriptBlock;
}

export function generateScript(
  scriptName: string,
  mode: ScriptMode,
  blocks: ScriptBlock[]
): string {
  const lines: string[] = [];
  lines.push('// Generated by ItsAstralMC Script API Editor');
  lines.push('');

  const imports = blocks.filter((block) => block.type === 'import');
  const body = blocks.filter((block) => block.type !== 'import');

  for (const imp of imports) {
    const target = imp.variableName?.trim() || '* as module';
    const path = imp.path?.trim() || './module';
    lines.push(`import ${target} from '${path}';`);
  }

  if (imports.length > 0 && body.length > 0) {
    lines.push('');
  }

  if (mode === 'function') {
    const fnName = scriptName.trim() || 'myFunction';
    lines.push(`export function ${fnName}(${body.length > 0 ? '...args' : ''}) {`);
    const functionBody = body.map((block) => generateBlockCode(block, 1));
    lines.push(...functionBody);
    lines.push('}');
  } else {
    for (const block of body) {
      lines.push(generateBlockCode(block, 0));
    }
  }

  return lines.join('\n');
}

function generateBlockCode(block: ScriptBlock, indentLevel: number): string {
  const indent = '  '.repeat(indentLevel);
  switch (block.type) {
    case 'import': {
      const target = block.variableName?.trim() || '* as module';
      const path = block.path?.trim() || './module';
      return `${indent}import ${target} from '${path}';`;
    }
    case 'variable': {
      const name = block.variableName?.trim() || 'myVar';
      const value = block.value?.trim() || 'undefined';
      return `${indent}const ${name} = ${value};`;
    }
    case 'function': {
      const fnName = block.functionName?.trim() || 'myFunction';
      const params = block.params?.trim() || '';
      const children = block.children.map((child) => generateBlockCode(child, indentLevel + 1));
      const body = children.length > 0 ? ['{', ...children, `${indent}}`] : ['{', `${indent}  // TODO`, `${indent}}`];
      return `${indent}function ${fnName}(${params}) ${body.join('\n').replace(/^/gm, '')}`;
    }
    case 'if': {
      const condition = block.condition?.trim() || 'true';
      const children = block.children.map((child) => generateBlockCode(child, indentLevel + 1));
      if (children.length === 0) {
        return `${indent}if (${condition}) {
${indent}  // TODO
${indent}}`;
      }
      return `${indent}if (${condition}) {
${children.join('\n')}
${indent}}`;
    }
    case 'console_log': {
      const formatted = block.message?.trim() || '""';
      return `${indent}console.log(${formatted});`;
    }
    case 'return': {
      const expression = block.expression?.trim() || 'undefined';
      return `${indent}return ${expression};`;
    }
    case 'expression': {
      const expression = block.expression?.trim() || '// expression';
      return `${indent}${expression}${expression.endsWith(';') ? '' : ';'}`;
    }
    default:
      return `${indent}// Unsupported block: ${block.type}`;
  }
}
